### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Doris927** [tammytangg/react-blog-demo#1]
# Todo List

- [ ] Home Page
- [ ] Blog Page - List 
- [ ] Blog Page - Ariticle
- [ ] Blog Page - Comments
- [ ] Blog Page - Archives
- [ ] Blog Page - Tag
- [ ] Blog Page - Editor 
- [ ] Demo Page - Time Line
- [ ] Resume Page

**Comment by Doris927** [comment]
Test Comment1

**Comment by Doris927** [comment]
Test Comment2
